---
title: "Functionality Flow"
output: rmarkdown::html_vignette
bibliography: references.bib
csl: vancouver.csl
vignette: >
  %\VignetteIndexEntry{Functionality Flow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(dplyr)
```

## Overview

The OSDC algorithm - and thereby, the `osdc` package - contains two
components:

-   [Extracting the diabetes
    population](#extracting-diabetes-population)
-   [Classifying the diabetes type (type 1 and
    type2)](#classifying-diabetes-type)

In the following sections, we will go through each of these components
and the functions they contain.

## Extracting the diabetes population {#extracting-diabetes-population}

This component extracts the diabetes population based on the following
five data sources (Danish names in parentheses):

-   The Register of Laboratory Results for Research, *RLRR*
    (Laboratoriedatabasens Forskertabel)
-   The Danish National Patient Registry, *DNPR*
    (Landspatientregisteret, *LPR*)
-   (Lægemiddelsdatabasen)
-   (CPR-registerets befolkningstabel, *BEF*)
-   The Health Service Register (Sygesikringsregisteret)

<!-- TODO: Add English translations for Lægemiddelsdatabasen and BEF -->

This component will have one user-facing function:
`extract_diabetes_population`. All five data sources are used as input
for this function.

As described in the [design](design.Rmd) vignette, the inclusion date is
the date of the second inclusion criteria. Inclusion events include:

-   HbA1c measurements of ≥48 mmol/mol
-   Hospital diagnoses of diabetes
-   Diabetes-specific services received at podiatrists
-   Purchase of glucose-lowering drugs (GLD)

Note that HbA1c tests and GLD purchases during pregnancies are excluded.
See section [Exclusion: HbA1c tests and GLD purchases during estimated
pregnancy windows](#exclusion-pregnancy-windows) for how pregnancy
windows are estimated. Glucose-lowering brand drugs for weight loss and
metformin purchases for women below age 40 are excluded as well.

This results in the functionality flow for extracting the diabetes
population seen below. All functions take a `data.frame` as input and
outputs a `data.frame`.

![Flow of functions for extracting a diabetes population using the
`osdc` package. The dark grey box denotes the user-facing function,
while the remaining boxes are internal functions. Green and red boxes
represent filtering functions (inclusion and exclusion events,
respectively).](images/diabetes-population-functions.png)

### Inclusion event: HbA1c tests above 48 mmol/mol

The function `include_hba1c_tests_over_48_mmol_per_mol` uses RLRR as
data source to extract all events of tests above 48 mmol/mol.

<!-- TODO: Add details on how this filtering should be done -->

### Inclusion event: Hospital diagnosis of diabetes

The function `include_diabetes_diagnoses` uses the hospital contacts
from DNPR to include all dates of diabetes diagnoses. Diabetes diagnoses
from both ICD 8 and ICD 10 are included.

This function contains two helper functions:

-   `extract_diabetes_diagnoses_icd_10`
-   `extract_diabetes_diagnoses_icd_8`

<!-- TODO: Add details on how this filtering should be done, e.g., diagnosis codes -->

<!-- TODO: Which specific ICD 8 and 10 codes are included? -->

### Inclusion event: Diabetes-specific podiatrist services

The function `include_diabetes_specific_podiatrist_services` uses the
Health Service Register to extract the dates of all diabetes-specific
podiatrist services.

<!-- TODO: Add details on how this filtering should be done -->

### Inclusion event: GLD purchases

The function `include_gld_purchases` uses Lægemiddelsdatabasen to
extract the dates of all GLD purchases.

<!-- TODO: Add English translation of data source -->

<!-- TODO: Add details on how this filtering should be done -->

Note: GLD purchases only include purchases from 1997 and onwards.

<!-- TODO: Add this + link to resource "For details about this, see [link]." -->

### Exclusion: HbA1c tests and GLD purchases during estimated pregnancy windows {#exclusion-pregnancy-windows}

The function `exclude_events_during_pregnancy_windows` uses diagnoses
from DNPR as a data source and is used to exclude both HbA1c tests and
GLD purchases during estimated pregnancy windows.

Under the hood, this relies on the function
`extract_pregnancy_index_dates` that contains the following three helper
functions:

-   `calculate_pregnancy_index_date_for_mc_visits_wo_end_date` (this
    might be removed with the inclusion of the birth register)
-   `extract_pregnancy_end_dates`
-   `extract_maternal_care_visit_dates_without_end_date`

<!-- TODO: Update whether `calculate_pregnancy_index_date_for_mc_visits_wo_end_date` will be removed. @Aastedet? -->

`extract_pregnancy_end_dates` extracts maternal care visits with an end
date and exclude visits between 40 weeks before end date to 12 weeks
after end date.

`extract_maternal_care_visit_dates_without_end_date` uses the output
from `extract_pregnancy_end_dates` which identifies maternal care visits
*with* end dates to derive maternal care visits *without* end dates.
below.
<!-- TODO: What is done with the mc visits without end dates then? -->

<!-- TODO: Add details on how this filtering should be done -->

### Exclusion: Glucose-lowering brand drugs for weight loss

The function `exclude_weight_loss_drugs` uses \*\* as a data source and
excludes **which brands**?

<!-- TODO: Add details on how this filtering should be done -->

<!-- TODO: Add data source and which brands are excluded -->

### Exclusion: Metformin purchases for women below age 40

The function `exclude_potential_pcos` uses BEF to exclude all purchases
of metformin by women below age 40 (i.e., \<= 39 years old) at the date
of purchase.

This function contains two helper functions:

-   `exclude_women`
-   `exclude_age_40_or_younger`

<!-- TODO: Add English translation of BEF -->

<!-- TODO: Add details on how this filtering should be done -->

### Extract raw inclusion dates

Then, the inclusion events from each inclusion criteria are joined in
the function `extract_raw_inclusion_dates`. For each individual with
inclusion events, the date of the *second* event is extracted as the
*raw* inclusion date, i.e., the date the OSDC algorithm defines as the
diagnosis date.

### Add stable inclusion dates

Finally, from the raw inclusion dates, a stable inclusion date column is
added. The column censors inclusion dates from time-periods of
insufficient data coverage. For details on this, see the [Description of
algorithm contents & logic](algorithm_logic.Rmd) vignette.

## Classifying the diabetes type {#classifying-diabetes-type}

The second component of the OSDC algorithm classifies individuals from
the extracted diabetes population as having either T1D or T2D. The
output of this component is a `data.frame` that includes one row per
individual in the diabetes population: one column with their PNR, two
columns with inclusion dates (one "stable" date and one "raw" date - see
the [Description of algorithm contents & logic](algorithm_logic.Rmd)
vignette for an elaboration on what that entails), and one column with
the diabetes type.

<!-- TODO: Make sure this is the correct link - and add a link specific to the specific section where this is described -->

This component will also have one user-facing function:
`classify_diabetes_type`. This function takes the output of
`extract_diabetes_population` as input.

### Type 1 classification

The classification of type 1 diabetes relies on the following two
filters. To be classified as having type 1 diabetes, individuals must
have:

1.  At least one T1D primary diagnosis and only purchased insulins
    (i.e., no purchases of any other type of GLDs), or
2.  A majority of T1D primary diagnoses, purchased insulin within 180
    days of diagnosis, and 2/3 of GLD doses are insulin.

Functions for the above filters are described in the following sections.

![Flow of functions for classifying the diabetes type using the `osdc`
package. The dark grey box denotes the user-facing function, while the
remaining boxes are internal
functions.](images/classify-diabetes-type-functions.png)

#### Filter 1: Any T1D diagnoses and all GLD purchases are insulins

The first filter includes two criteria: 1) Whether individuals have any
T1D diagnoses and 2) whether all GLD purchases are insulin.

Thus, this filter contains two functions:

1.  `t1d_include_at_least_one_t1d_primary_diagnosis`, which relies on
    the hospital diagnoses from DNPR extracted in component 1.
2.  `t1d_include_only_purchased_insulins` which relies on the GLD
    purchases from Lægemiddelsdatabasen.

<!-- TODO: Add English translations for Lægemiddelsdatabasen  -->

#### Filter 2: Majority of T1D primary diagnoses, insulin within 180 days of diagnosis, and insulin constitutes 2/3 of all GLD doses

The second filter includes three criteria: 1) Whether individuals have a
majority of T1D primary diagnoses, 2) whether they purchased insulin
within 180 days of diagnosis, and 3) whether insulin constitutes 2/3 of
all their GLD doses.

This results in three functions:

1.  `t1d_include_majority_of_t1d_primary_diagnoses` (as compared to T2D
    diagnoses) which again relies on primary hospital diagnoses from
    DNPR.
2.  `t1d_include_insulin_purchase_within_180_days_of_diagnosis` which
    relies on both diagnosis from DNPR and GLD purchases from
    Lægemiddelsdatabasen.
3.  `t1d_include_two_thirds_of_purchased_gld_doses_are_insulin` which
    relies on the GLD purchases from Lægemiddelsdatabasen.

Note that in the first function, individuals must have a majority of T1D
primary diagnoses from endocrinological departments (or from other
medical departments, in the absence of contacts to endocrinological
departments).

### Type 2 classification

As described in the [design](design.Rmd) vignette, individuals not
classified as type 1 cases are classified as type 2 cases.

## Output

The output of the second component, and therefore, the OSDC algorithm is
a `data.frame` which includes four columns:

1.  **PNR**: The pseudonymised social security number of individuals in
    the diabetes population (one row per individual)
2.  **stable_inclusion_date**: The *stable* inclusion date (i.e., the
    raw date mutated so only individuals included in the time-period
    where data coverage is sufficient to make incident cases reliable)\*
    <!-- TODO: Specify this time-period: e.g., later than 1997 -->
3.  **raw_inclusion_date**: The *raw* inclusion date (i.e., the date of
    the second inclusion event as described in the [Extracting the
    diabetes population](#extracting-diabetes-population) section above)
4.  **diabetes_type** The classified diabetes type

\*For more information on the "raw" versus "stable" inclusion date, see
the [Description of algorithm contents & logic](algorithm_logic.Rmd)
vignette.

<!-- TODO: Make sure this is the correct link - and add a link specific to the specific section where this is described -->

For an example, see below.

| PNR        | stable_inclusion_date | raw_inclusion_date | diabetes_type |
|------------|-----------------------|--------------------|---------------|
| 0000000001 | 01-01-2020            | 01-01-2020         | T1D           |
| 0000000004 | NULL                  | 19-04-1995         | T2D           |

: Example rows of the `data.frame` output of the `osdc` package.

The individuals `0000000001` and `0000000004` have been classified as
having diabetes (`T1D` and `T2D`, respectively). `0000000004` is
classified as having type 1 diabetes (T1D) with an inclusion date of
`01-01-2020`. Since this date is within a time-period of sufficient data
coverage, the column `stable_inclusion_date` is populated with the same
date as `raw_inclusion_date`.

The individual in the second row, `0000000004` is classified as having
type 2 diabetes `T2D` with an inclusion date of `19-04-1995`. Since 1995
is within a time-period of insufficient data coverage,
`stable_inclusion_date` is `NULL`. However, `raw_inclusion_date` still
contains the inclusion date of this individual.

<!-- TODO: Specify the "stable" time-period: e.g., later than 1997 -->
