@startuml create-lpr2
!theme cerulean-outline
<style>
action, card, database, rectangle {
    FontColor black
}
</style>

together {
    database lpr_diag
    database lpr_adm
}

action "keep_needed_diagnosis_code()" as code
action "keep_needed_diagnosis_type()" as type
action "join_lpr2()" as join
action "get_department()" as gd
action "get_t1d()" as t1d
action "get_t2d()" as t2d
action "get_primary_diagnosis()" as gpd

lpr_diag --> code 
code --> type
type --> join
lpr_adm --> join
join --> gd
gd --> t1d
t1d --> t2d
t2d --> gpd
}

@enduml
