@startuml diabetes-population-functions 

#darkgrey: Extract_diabetes_population;

switch (Extract dates of inclusion events)
case ( HbA1c tests)
    #lightgreen:include_hba1c_tests_over_48_mmol_per_mol;
    #pink:exclude_events_during_pregnancy_windows;

case ( Hospital diabetes\n diagnosis)
    #lightgreen:include_diabetes_diagnoses;

case ( Diabetes-specific\n podiatrist services)
    #lightgreen:include_diabetes_specific_podiatrist_services;

case ( GLD purchases)
    #lightgreen:include_gld_purchases;
    #pink:exclude_events_during_pregnancy_windows;
    #pink:exclude_potential_pcos;
    #pink:exclude_purchases_of_weight_loss_drugs;
endswitch

:extract_classification_dates;

@enduml