@startuml diabetes-population-functions 

title Functions for extracting a diabetes population using OSDC

#darkgrey: Extract_diabetes_population;


switch (Extract Dates of Inclusion Events)
case ( Dates of\n HbA1c Tests)
    :include_dates_of_hba1c_tests_over_48_mmol_per_mol;
    :exclude_dates_during_pregnancy_windows;
case ( Dates of\n Diabetes Diagnosis)
    :include_dates_of_diabetes_diagnoses (ICD 8 and 10);
case ( Dates of\n Diabetes-Specific Podiatrist Services)
    :include_dates_of_diabetes_specific_podiatrist_services;
case ( Dates of\n GLD Purchases)
    :include_dates_of_gld_purchases;
    :exclude_dates_during_pregnancy_windows;
    :exclude_dates_of_potential_pcos;
    :exclude_dates_of_weight_loss_drug_purchases;
endswitch

:join_inclusion_events;
:extract_classification_dates;

center footer \nDark grey box: User-facing functions; Light grey boxes: Internal functions;

@enduml