@startuml functions-exclusion-pregnancy-window

title Exclusion: Pregnancy Window\nData Source: DNPR\n\nTo be used to filter both gld and hbA1c inclusion events

start
-> Exclude Event During Pregnancy\nData Source: DNPR;
#darkgrey:**exclude_events_during_pregnancy_windows(data: data.table) -> data.table**;
:**extract_pregnancy_index_dates(data: data.table) -> data.table**
- This function will extract pregnancy index dates using diagnoses (ICD 8 and 10?) from DNPR; 

:**Helper function: extract_pregnancy_end_dates(data: data.table) -> data.table**
- This might be removed with the inclusion of birth register;

:**Helper function: extract_maternal_care_visit_dates_without_end(data: data.table) -> data.table**
- Extract mc visits with end date (visits between 40 weeks before end date to 12 weeks after end date)
- Use these to identify mc visits without end dates to be used in the function below;

:**Helper function: calculate_pregnancy_index_date_based_mc_visits_wo_end_dates(data.table) -> data.table**;
stop

@enduml