@startuml function-flow
!theme cerulean-outline
<style>
action {
    FontColor black
}
database {
    FontColor black
}
.inclusion {
    BackgroundColor lightblue
}
.exclusion {
    BackgroundColor orange
}
</style>

hide <<inclusion>> stereotype
hide <<exclusion>> stereotype

card classify_diabetes() as cd {
    together {
        database sssy
        database sysi
        database lpr_diag
        database lpr_adm
        database lmdb
        database lab_forsker
        database kontakter
        database diagnoser
        database bef
    }

    action "get_pregnancy_dates()" as pregnancy
    action "get_potential_pcos()" as pcos
    action "get_diagnosis_date()" as diagnosis_date
    action "join_lpr2()" as lpr2
    action "join_lpr3()" as lpr3

    together {
        action "exclude_pregnancy()" as ex_pregnancy <<exclusion>>
        action "exclude_purchases_of_weight_loss_drugs()" as ex_wld <<exclusion>>
        action "exclude_potential_pcos()" as ex_pcos <<exclusion>>
    }

    together {
        action "include_hba1c()" as in_hba1c <<inclusion>>
        action "include_diabetes_diagnosis()" as in_diagnosis <<inclusion>>
        action "include_podiatrist_services()" as in_podiatrist <<inclusion>>
        action "include_purchases_gld()" as in_gld <<inclusion>>
    }

    action "join_inclusion()" as join_inclusion
    action "get_diagnosis_date()" as diagnosis_date

'join lpr
    lpr_diag --> lpr2
    lpr_adm --> lpr2
    kontakter --> lpr3
    diagnoser --> lpr3

'inclusion: podiatrist services
    sssy --> in_podiatrist
    sysi --> in_podiatrist
    in_podiatrist --> join_inclusion

'inclusion: hba1c
    lab_forsker --> in_hba1c
    in_hba1c --> ex_pregnancy
    ex_pregnancy --> join_inclusion

'inclusion: gld purchases
    lmdb --> in_gld
    in_gld --> ex_pcos
    ex_pcos --> ex_wld
    ex_wld --> ex_pregnancy

'inclusion: diabetes diagnosis
    lpr2 --> in_diagnosis
    lpr3 --> in_diagnosis
    in_diagnosis --> join_inclusion

'helper functions
    lpr2 --> pregnancy
    lpr3 --> pregnancy
    pregnancy --> ex_pregnancy
    lmdb --> wld
    wld --> ex_wld
    bef --> pcos
    in_gld --> ex_pcos
    pcos --> ex_pcos
    join_inclusion --> diagnosis_date

'Diabetes type classification

    rectangle Classification {
        action "get_has_t1d_primary_diagnosis()" as t1d_diagnosis
        action "get_only_insulin_purchases()" as only_insulins
        action "get_majority_of_t1d_primary_diagnoses()" as t1d_diagnosis_majority
        action "get_insulin_purchase_within_180_days()" as insulin_within_180_days
        action "get_insulin_is_two_thirds_of_gld_doses()" as insulin_is_two_thirds
    }

    diagnosis_date --> t1d_diagnosis
    t1d_diagnosis -l-> only_insulins
    only_insulins -d-> t1d_diagnosis_majority
    t1d_diagnosis_majority -r-> insulin_within_180_days
    insulin_within_180_days -r-> insulin_is_two_thirds
    

}
@enduml
