@startuml function-flow
!theme cerulean-outline
<style>
action {
    FontColor black
}
database {
    FontColor black
}
.inclusion {
    BackgroundColor lightblue
}
.exclusion {
    BackgroundColor orange
}
</style>

hide <<inclusion>> stereotype
hide <<exclusion>> stereotype

card classify_diabetes_status() as cd {
    together {
        database sssy
        database sysi
        database lpr_diag
        database lpr_adm
        database lmdb
        database lab_forsker
        database kontakter
        database diagnoser
        database bef
    }

    action "get_pregnancy_dates()" as pregnancy
    action "get_pcos()" as pcos
    action "get_diagnosis_date()" as diagnosis_date

    together {
        action "exclude_pregnancy()" as ex_pregnancy <<exclusion>>
        action "exclude_purchases_weight_loss_drugs()" as ex_wld <<exclusion>>
        action "exclude_pcos()" as ex_pcos <<exclusion>>
    }

    together {
        action "include_hba1c()" as in_hba1c <<inclusion>>
        action "include_diabetes_diagnosis()" as in_diagnosis <<inclusion>>
        action "include_podiatrist_services()" as in_podiatrist <<inclusion>>
        action "include_purchases_gld()" as in_gld <<inclusion>>
    }

    lab_forsker --> in_hba1c
    in_hba1c --> ex_pregnancy

    lpr_diag --> pregnancy
    lpr_adm --> pregnancy
    kontakter --> pregnancy
    diagnoser --> pregnancy
    pregnancy -> ex_pregnancy

    lpr_diag --> in_diagnosis
    lpr_adm --> in_diagnosis
    kontakter --> in_diagnosis
    diagnoser --> in_diagnosis

    sssy --> in_podiatrist
    sysi --> in_podiatrist
    
    lmdb --> in_gld
    in_gld --> ex_pregnancy
    in_gld --> ex_wld

    bef --> pcos
    in_gld --> ex_pcos
    pcos --> ex_pcos

    ex_wld --> diagnosis_date
    ex_pregnancy --> diagnosis_date
    ex_pcos --> diagnosis_date
    in_podiatrist --> diagnosis_date
    in_diagnosis --> diagnosis_date

}
@enduml
