@startuml functions-overall

title Overview of Functions to Used to Create an OSDC Population

#darkgrey:**Extract Diabetes Population**
User-Facing Function: extract_diabetes_population(index_date: date, data_sources: list[data.table]) -> data.table;
:**Inclusion Criteria**

**HbA1c Tests (=>48 mmol/mol) (RLRR)**
  - Function: include_hba1c_tests_over_threshold(
    data: data.table, threshold: int = 48) -> data.table

**Purchase of Glucose Lowering Drugs (GLDs) (Lægemiddelsdatabasen)**:
  - Function: include_gld_purchases(data: data.table) -> data.table

**Hospital Diagnosis of Diabetes (DNPR) **
  - Function: include_diabetes_diagnoses(data: data.table) -> data.table
      - include_diabetes_diagnoses_icd_10(data: data.table) -> data.table
      - include_diabetes_diagnoses_icd_8(data: data.table) -> data.table

**Health Services (Diabetes-specific Podiatrist Services)**
  - Function: include_podiatrist_services(data: data.table) -> data.table
      - placeholder helper functions;

:**Exclusion Criteria**

**HbA1c and GLD: Events during pregnancies (potential GDM) (DNPR)**
    - Function: exclude_events_during_pregnancy_windows(data: data.table) -> data.table
       - extract_pregnancy_index_dates(data: data.table) 
          -> data.table
        - calculate_pregnancy_index_date_for_mc_visits_wo_end_dates(
            data.table) -> data.table
        - extract_pregnancy_end_dates(data: data.table) -> data.table
        - extract_maternal_care_visit_dates_without_end(
            data: data.table) -> data.table

**GLD: Metformin purchase for women below age 40 (potential PCOS)**
    - Functions: exclude_potential_pcos(data: data.table, 
      sex: str = "F", age: int = 40) -> data.table

**Weight Loss Drugs: Purchase of brand drugs for weight loss, e.g., Saxenda.**
'GLD only?
    - Function: exclude_weight_loss_drugs(data: data.table) -> data.table;

:**Classification Date:**
    - Functions: 
        - join_inclusion_events(data: list[data.table]) -> data.table
        - extract_second_inclusion_event_date(data: data.table) -> data.table;

#darkgrey:**Classify Diabetes Type**
User-Facing Function: classify_diabetes_type(data: data.table) -> data.table;


:**Type 2 Diabetes**

**Inclusion Criteria:**

**Any purchases of Non-Insulin GLDs**
- Function: include_any_non_insulin_gld_purchases(data: data.table) -> data.table

**Most recent type-specific diabetes diagnosis is hospital diagnosis of type 2 diabetes**
- Function: include_latest_diabetes_diagnosis_is_type_2(data: data.table) -> data.table

**Exclusion Criteria:**

**Women that have purchased only metformin and have any diagnoses of PCOS or have**
**purchases of clomifene or combination drugs containing antiandrogens and oestrogens**
- Functions: 
    - exclude_women_with_only_metformin_purchases(data: data.table) -> data.table
    - exclude_women_with_psoc_diagnoses(data: data.table) -> data.table
    - exclude_women_with_combination_drug_purchases(data: data.table) -> data.table

**No recorded inclusion events in the last 10 years prior to the most recent date**
**available for the individual (index date)**
;

:**Type 1 Diabetes**

**Inclusion Criteria:**

**Any purchases of insulin drugs.**

**A hospital diagnosis of type 1 diabetes as the most recent**

**type-specific diabetes diagnosis.**

**Exclusion criteria:**

**Women with any diagnoses of gestational diabetes mellitus, who have purchased**
**glucose-lowering drugs only in the period from 280 days prior to their first**
**diagnosis of gestational diabetes mellitus until 280 days after their last diagnosis.**

**No purchases of glucose-lowering drugs or only one purchase and no hospital records of**
**type 1 diabetes.**

**No insulin drug purchases in the last 10 years prior to the index date.**
;

#palegreen:OSDC Population Created;
kill

'Do we want to support export? (e.g. to csv, parquet, SASS?)

@enduml
