#' List of non-cases to test the diabetes classification algorithm
#'
#' This function generates a list of tibbles representing the Danish health
#' registers and the data necessary to run the algorithm. The dataset contains
#' individuals who should *not* be included in the final classified cohort.
#'
#' The generated data is used in `testthat` tests to ensure the algorithm
#' behaves as expected under a wide range of conditions, but it is also intended
#' to be explored by users to better understand how the algorithm logic works
#' and to be shown in the documentation.
#'
#' @return A named list of 9 [tibble::tibble()] objects, each representing a
#'   different health register: `bef`, `lmdb`, `lpr_adm`, `lpr_diag`,
#'   `kontakter`, `diagnoser`, `sysi`, `sssy`, and `lab_forsker`.
#' @export
#'
#' @examples
#' cases()
non_cases <- function() {
  sim_data <- registers() |>
    names() |>
    simulate_registers(n = 1000)

  bef <- tibble::tribble(
    ~pnr, ~koen, ~foed_dato,
    "nc_pcos_1", 2, "19800101",
    "nc_pcos_2", 2, "19800101",
    "nc_pcos_3", 2, "19800101"
  ) |>
    dplyr::mutate(koen = as.integer(.data$koen)) |>
    dplyr::bind_rows(sim_data$bef)

  lmdb <- tibble::tribble(
    ~pnr, ~volume, ~eksd, ~atc, ~apk, ~indo,
    "nc_pcos_1", 10, "20210101", "A10BA02", 5, "0000276",
    "nc_pcos_2", 10, "20190101", "A10BA02", 5, "0000000",
    "nc_pcos_3", 10, "20190101", "A10BA02", 5, "0000276"
  ) |>
    dplyr::bind_rows(sim_data$lmdb)

  lpr_adm <- tibble::tribble(
    ~pnr, ~c_spec, ~recnum, ~d_inddto,
  ) |>
    dplyr::bind_rows(sim_data$lpr_adm)

  lpr_diag <- tibble::tribble(
    ~recnum, ~c_diag, ~c_diagtype,
  ) |>
    dplyr::bind_rows(sim_data$lpr_diag)

  kontakter <- tibble::tribble(
    ~cpr, ~dw_ek_kontakt, ~hovedspeciale_ans, ~dato_start,
  ) |>
    dplyr::bind_rows(sim_data$kontakter)

  diagnoser <- tibble::tribble(
    ~dw_ek_kontakt, ~diagnosekode, ~diagnosetype, ~senere_afkraeftet,
  ) |>
    dplyr::bind_rows(sim_data$diagnoser)

  sysi <- tibble::tribble(
    ~pnr, ~barnmak, ~speciale, ~honuge,
  ) |>
    dplyr::mutate(barnmak = as.integer(.data$barnmak)) |>
    dplyr::bind_rows(sim_data$sysi)

  sssy <- tibble::tribble(
    ~pnr, ~barnmak, ~speciale, ~honuge,
  ) |>
    dplyr::mutate(barnmak = as.integer(.data$barnmak)) |>
    dplyr::bind_rows(sim_data$sssy)

  lab_forsker <- tibble::tribble(
    ~patient_cpr, ~samplingdate, ~analysiscode, ~value,
  ) |>
    dplyr::bind_rows(sim_data$lab_forsker)

  # Combine all tibbles into a named list -----

  list(
    bef = bef,
    lmdb = lmdb,
    lpr_adm = lpr_adm,
    lpr_diag = lpr_diag,
    kontakter = kontakter,
    diagnoser = diagnoser,
    sysi = sysi,
    sssy = sssy,
    lab_forsker = lab_forsker
  )
}

#' Description of the different non-cases included in `non_cases()`
#'
#' @returns A named list of character strings, where each name corresponds to a
#'  non-case PNR in the dataset generated by `non_cases()`.
#' @export
#'
#' @examples
#' non_cases_metadata()
non_cases_metadata <- function() {
  list(
    nc_pcos_1 = "Woman taking metformin, older than 40, and has an indication code.",
    nc_pcos_2 = "Woman taking metformin, younger than 40, and doesn't have the indication code.",
    nc_pcos_3 = "Woman taking metformin, younger than 40, and has an indication code."
  )
}
