name: Assign author to their PR

on:
  pull_request:
    types:
      - reopened
      - opened

permissions:
  pull-requests: write

jobs:
  assign-author-to-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to author
        run: |
          gh pr edit $PR --add-assignee $AUTHOR
        env:
          AUTHOR: ${{ github.event.pull_request.user.login }}
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

