name: Test, build, and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  check:
    uses: .github/workflows/R-CMD-check.yaml@main

  coverage:
    uses: .github/workflows/test-coverage.yaml@main
    needs: check

  deploy:
    uses: .github/workflows/pkgdown.yaml@main
    needs: coverage
